import { mkdir, writeFile, cp, rm } from 'node:fs/promises';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {site, copy} from './content/site.mjs';
import {policies} from './content/policies.mjs';
const root=path.dirname(fileURLToPath(import.meta.url));
const out=path.join(root,'dist');
const release=process.argv.includes('--release');
const basePath=(process.env.KNISTERTAP_BASE_PATH||'').replace(/\/$/,'');
if(basePath && !/^\/(?:[A-Za-z0-9_-]+\/)*[A-Za-z0-9_-]+$/.test(basePath)) throw new Error('KNISTERTAP_BASE_PATH must be empty or a repository path such as /knistertap.');
// Prefix only local root-relative URLs; external citations, mailto links and fragments stay intact.
async function writeHTML(file,html){await writeFile(file,html.replace(/((?:href|src)="|url=)\/(?!\/)/g,(_,prefix)=>prefix+basePath+'/'));}
if(release && (!site.legalReviewed || !/^https:\/\//.test(site.domain) || !/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(site.email) || /\[[A-ZÄÖÜ]/.test(JSON.stringify(policies)))) throw new Error('Release requires reviewed policies without placeholders, a public HTTPS domain, and a support email. Draft builds remain available with npm run build.');
const e=(s='')=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'})[c]);
const br=s=>e(s).replaceAll('&lt;br&gt;','<br>');
function analyticsScript(){
 const a=site.analytics;
 if(!a?.scriptUrl && !a?.websiteId) return '';
 if(a.provider!=='umami' || new URL(a.scriptUrl).protocol!=='https:' || !/^[0-9a-f]{8}(?:-[0-9a-f]{4}){3}-[0-9a-f]{12}$/i.test(a.websiteId) || !Array.isArray(a.domains) || !a.domains.length || a.domains.some(d=>!/^[a-z0-9.-]+$/i.test(d))) throw new Error('Umami requires an HTTPS script URL, website UUID and allowed domains.');
 return `<script defer src="${e(a.scriptUrl)}" data-website-id="${e(a.websiteId)}" data-domains="${e(a.domains.join(','))}"></script>`;
}

const url=(lang,page='')=>`/${lang}/${page ? page+'/' : ''}`;
const arrow='<span aria-hidden="true">↗</span>';
const star='<svg aria-hidden="true" width="32" height="32" viewBox="0 0 32 32"><path d="M16 0C20 10 22 12 32 16C22 20 20 22 16 32C12 22 10 20 0 16C10 12 12 10 16 0Z" fill="currentColor"/></svg>';
const link=(href,text,cls='')=>`<a ${cls?`class="${cls}"`:''} href="${e(href)}">${text}</a>`;
const appStoreBadge=(lang,game)=>link(game.appStoreUrl,`<img src="/assets/app-store-badge-${lang}.svg" alt="${e(copy[lang].available)}" width="120" height="40">`,'app-store-badge');
function header(lang,page){const c=copy[lang],nav=`${link(url(lang)+'#games',e(c.games))}${link(url(lang)+'#mission',e(c.mission))}${link(url(lang,'support'),e(c.support))}`;return `<a class="skip" href="#main">${e(c.skip)}</a><header class="header"><a class="brand" href="${url(lang)}" aria-label="Knistertap">${star}<span>knistertap</span></a><nav class="desktop-nav" aria-label="${e(c.menu)}">${nav}</nav><nav class="languages" aria-label="Language"><a lang="en" hreflang="en" href="${url('en',page)}" ${lang==='en'?'aria-current="true"':''}>EN</a><a lang="de" hreflang="de" href="${url('de',page)}" ${lang==='de'?'aria-current="true"':''}>DE</a></nav><details class="mobile-menu"><summary aria-label="${e(c.menu)}"><span></span><span></span></summary><nav aria-label="${e(c.menu)}">${nav}</nav></details></header>`;}
function footer(lang){const c=copy[lang];return `<footer class="footer"><div><a class="wordmark" href="${url(lang)}">knistertap</a><p>${e(c.headline.join(' '))}</p></div><nav aria-label="${e(c.legal)}">${['support','privacy','terms','legal'].map(k=>link(url(lang,k),e(c[k]))).join('')}<span>© 2026 Knistertap</span></nav></footer>`;}
function supportStrip(lang){const c=copy[lang];return `<section class="support-strip"><div><h2>${e(c.stuck)}</h2><p>${e(c.stuckBody)}</p></div>${link(url(lang,'support'),e(c.visitSupport)+arrow,'button outline')}</section>`;}
function heroArt(lang){const c=copy[lang];return `<div class="hero-art" aria-hidden="true"><div class="play-card"><div class="play-caption"><span>${e(c.spark)}</span><span>01 / ∞</span></div><div class="play-tiles">${[...'WÖRTLI'].map((l,i)=>`<span class="${i===1?'yellow':''}">${l}</span>`).join('')}</div><div class="play-bottom">${e(c.less)}</div></div><div class="sticker">${br(c.sticker)}</div><svg class="doodle" width="86" height="90" viewBox="0 0 86 90"><path d="M42 7L45 28M70 17L56 35M79 48L60 48M62 78L52 61M29 81L35 62M7 56L25 50M12 21L28 35" stroke="currentColor" stroke-width="5" stroke-linecap="round" fill="none"/></svg></div>`;}
function wordRows(){return `<div class="word-rows" aria-hidden="true">${['SPIEL','WORTE'].map((s,row)=>`<div>${[...s].map((l,i)=>`<span class="${row?'green':i===3?'gold':'grey'}">${l}</span>`).join('')}</div>`).join('')}</div>`;}
function brainAnswers(lang){return copy[lang].brainFaq.map((item,i)=>`<details id="faq-${item.id}" ${i===0?'open':''}><summary>${e(item.question)}</summary>${item.paragraphs.map(p=>`<p>${e(p)}</p>`).join('')}<div class="research-sources">${item.sources.map(([label,href])=>link(href,e(label)+' ↗')).join('')}</div></details>`).join('');}
function brainFAQ(lang){const c=copy[lang];return `<section id="faq" class="brain-faq" aria-labelledby="faq-title"><div class="faq-intro"><p class="eyebrow blue">${e(c.faqLabel)}</p><h2 id="faq-title">${br(c.faqTitle)}</h2><p>${e(c.faqIntro)}</p></div><div class="faq">${brainAnswers(lang)}</div></section>`;}
function homepage(lang){const c=copy[lang];return `<main id="main"><section class="hero"><div class="hero-copy"><p class="eyebrow dot">${e(c.eyebrow)}</p><h1>${c.headline.map(e).join('<br>')}</h1><p class="lead">${e(c.intro)}</p><div class="hero-actions">${link('#games',e(c.cta)+arrow,'button primary')}<span>${e(c.indie)}</span></div></div>${heroArt(lang)}</section><section id="games" class="games"><div class="section-heading"><div><p class="eyebrow">${e(c.shelf)}</p><h2>${e(c.shelfTitle)}</h2></div><p>${br(c.shelfNote)}</p></div><div class="game-shelf">${site.games.map(g=>`<article class="game-card"><div class="game-head"><div class="game-name"><img src="${g.icon}" alt="${e(g.name)}" width="72" height="72"><div><h3>${e(g.name)}</h3><p>${e(c.gameTag)}</p></div></div><span class="status">${e(c.status)}</span></div><div class="game-preview">${wordRows()}<p>${e(c.gameBody)}</p></div><div class="game-foot"><span>${e(c.gameMeta)}</span></div><div class="game-actions">${g.appStoreUrl?appStoreBadge(lang,g):''}${link(url(lang,'games/'+g.id),e(c.gameMore)+arrow,'game-more')}</div></article>`).join('')}<article class="next-game"><div class="next-top"><div class="question-mark" aria-hidden="true">?</div><span>${e(c.nextLabel)}</span></div><div><h3>${br(c.nextTitle)}</h3><p>${e(c.nextBody)}</p>${link('#mission',e(c.makerLink)+' <span aria-hidden="true">↓</span>')}</div></article></div></section><section id="mission" class="mission"><div class="mission-heading"><p class="eyebrow">${e(c.missionLabel)}</p><h2>${br(c.missionTitle)}</h2><div class="note-sticker">${e(c.curiosity)}</div></div><div class="maker-note"><p class="mission-lead">${e(c.missionLead)}</p><p>${e(c.missionBody)}</p><p>${e(c.missionBody2)}</p><div class="signature">${star}<span>${e(c.founder)}</span></div><details class="research-note"><summary>${e(c.researchTitle)}</summary><p>${e(c.research)}</p></details></div></section>${brainFAQ(lang)}${supportStrip(lang)}</main>`;}
function support(lang){const c=copy[lang];return `<main id="main"><section class="page-intro"><p class="eyebrow blue">${e(c.supportLabel)}</p><h1>${e(c.supportTitle)}</h1><p class="lead">${e(c.supportIntro)}</p></section><section class="support-layout"><div class="faq" id="faq">${brainAnswers(lang)}${c.faq.map(([q,a],i)=>`<details ${i===0?'open':''}><summary>${e(q)}</summary><p>${e(a)}${i===2?' '+link(url(lang,'privacy'),e(c.privacy)):''}</p></details>`).join('')}</div><aside class="contact-card"><h2>${e(c.contactTitle)}</h2><p>${e(c.contactBody)}</p>${site.email?link('mailto:'+site.email,e(c.emailButton)+arrow,'button primary'):`<p class="contact-pending">${e(c.emailPending)}</p>`}${link(url(lang,'legal'),e(c.legal))}</aside></section></main>`;}
function formatPolicy(body){return body.split('\n').map(line=>`<p class="${line.startsWith('[')?'editor-note':''}">${e(line).replaceAll('support@knistertap.com',link('mailto:support@knistertap.com','support@knistertap.com')).replace(/\/(en|de)\/legal\//g,(u,l)=>link(u,l==='de'?'Impressum':'Legal notice (Impressum)')).replace(/https:\/\/[^\s<>]+/g,u=>{const plain=u.replace(/\.$/,'');return `<a href="${plain}">${plain}</a>${u.endsWith('.')?'.':''}`;})}</p>`).join('');}
function policyPage(lang,key){const c=copy[lang],p=policies[lang][key];return `<main id="main"><section class="page-intro legal-intro"><p class="eyebrow">${e(c.legalLabel)}</p><h1>${e(p.title)}</h1><p class="lead">${e(p.intro)}</p>${!release && p.draft!==false?`<p class="draft-notice">${e(c.draft)}</p>`:''}</section><div class="policy-layout"><nav class="legal-nav" aria-label="${e(c.legal)}">${['privacy','terms','legal','support'].map(k=>`<a href="${url(lang,k)}" ${key===k?'aria-current="page"':''}>${e(c[k])}</a>`).join('')}</nav><article class="policy-copy">${p.sections.map(([title,body],i)=>`<section id="${key==='privacy'&&i===3?'woertli':'section-'+(i+1)}"><h2><span>${String(i+1).padStart(2,'0')}</span>${e(title)}</h2>${formatPolicy(body)}</section>`).join('')}</article></div></main>`;}
function gamePage(lang){const c=copy[lang],g=site.games[0];return `<main id="main"><section class="hero game-detail"><div class="hero-copy">${link(url(lang)+'#games','← '+e(c.back),'back-link')}<img class="detail-icon" src="${g.icon}" alt="Wörtli" width="96" height="96"><h1>${br(c.gameDetailTitle)}</h1><p class="lead">${e(c.gameDetailIntro)}</p>${g.appStoreUrl?`<div class="hero-actions">${appStoreBadge(lang,g)}</div><p class="download-note">${e(c.releaseBody)}</p>`:''}</div>${heroArt(lang)}</section><section class="features">${c.features.map(([title,body],i)=>`<article><span class="feature-number">0${i+1}</span><h2>${e(title)}</h2><p>${e(body)}</p></article>`).join('')}</section><div class="game-legal-links">${link(url(lang,'privacy')+'#woertli',e(c.privacy))}${link(url(lang,'terms'),e(c.terms))}${link(url(lang,'support'),e(c.support))}</div>${supportStrip(lang)}</main>`;}
function document(lang,page,title,body){const c=copy[lang],description=page?c.intro:c.intro;return `<!doctype html><html lang="${lang}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#3157E8"><title>${e(title)} · Knistertap</title><meta name="description" content="${e(description)}">${!release?'<meta name="robots" content="noindex,nofollow">':''}<meta property="og:title" content="${e(title)} · Knistertap"><meta property="og:description" content="${e(c.intro)}"><meta property="og:type" content="website"><link rel="icon" href="/assets/favicon.svg" type="image/svg+xml"><link rel="stylesheet" href="/assets/fonts.css"><link rel="stylesheet" href="/assets/site.css">${site.domain?`<link rel="canonical" href="${e(site.domain+basePath+url(lang,page))}">`:''}<link rel="alternate" hreflang="en" href="${url('en',page)}"><link rel="alternate" hreflang="de" href="${url('de',page)}">${analyticsScript()}</head><body>${header(lang,page)}${body}${footer(lang)}</body></html>`;}
await rm(out,{recursive:true,force:true});await mkdir(out,{recursive:true});await cp(path.join(root,'public'),out,{recursive:true});
for(const lang of ['en','de']){
 const pages={'':homepage(lang),support:support(lang),'games/woertli':gamePage(lang),...Object.fromEntries(['privacy','terms','legal'].map(k=>[k,policyPage(lang,k)]))};
 for(const [page,html] of Object.entries(pages)){const directory=path.join(out,lang,page);await mkdir(directory,{recursive:true});await writeHTML(path.join(directory,'index.html'),document(lang,page,page?(policies[lang][page]?.title|| (page==='support'?copy[lang].support:'Wörtli')):copy[lang].headline.join(' '),html));}
 for(const [key,p] of Object.entries(policies[lang]))await writeFile(path.join(root,'docs',`${key}.${lang}.md`),`# Knistertap — ${p.title}\n\n${p.draft===false?'> Updated / Stand: 2026-09-09':'> DRAFT / ENTWURF · 2026-09-09 · Replace bracketed editorial notes and review before publication.'}\n\n${p.intro}\n\n${p.sections.map(([title,body],i)=>`## ${i+1}. ${title}\n\n${body}`).join('\n\n')}\n`);
 await writeFile(path.join(root,'docs',`faq.${lang}.md`),`# ${copy[lang].faqTitle.replaceAll('<br>',' ')}\n\n${copy[lang].brainFaq.map(item=>`## ${item.question}\n\n${item.paragraphs.join('\n\n')}\n\n${item.sources.map(([label,href])=>`[${label}](${href})`).join(' · ')}`).join('\n\n')}\n`);
 await writeFile(path.join(root,'docs',`mission.${lang}.md`),`# ${copy[lang].headline.join(' ')}\n\n## ${copy[lang].missionTitle.replaceAll('<br>',' ')}\n\n${['missionLead','missionBody','missionBody2','research'].map(k=>copy[lang][k]).join('\n\n')}\n`);
}
await writeHTML(path.join(out,'index.html'),document('en','',copy.en.headline.join(' '),homepage('en')));
for(const page of ['privacy','terms','legal','support']){await mkdir(path.join(out,page),{recursive:true});await writeHTML(path.join(out,page,'index.html'),`<!doctype html><html lang="en"><meta charset="utf-8"><meta http-equiv="refresh" content="0;url=/en/${page}/"><meta name="robots" content="noindex"><title>Knistertap</title><a href="/en/${page}/">${copy.en[page]}</a></html>`);}
await writeFile(path.join(out,'robots.txt'),release?'User-agent: *\nAllow: /\n':'User-agent: *\nDisallow: /\n');
console.log(`Built Knistertap: English and German pages + editable policy drafts. Mode: ${release?'release':'preview (noindex)'}.`);
