// Editorial drafts. Brackets identify information or decisions the operator must supply.
export const policies = {
  en: {
    privacy: {
      title: 'Privacy Policy',
      intro: 'This notice explains how Knistertap handles personal information when you visit this website, contact the developer, or use a game listed below. Game-specific sections supplement the shared information; they do not imply that every game processes the same data.',
      sections: [
        ['Who is responsible?', 'The operator’s identity and postal address are listed in the legal notice: /en/legal/. This operator is responsible for the processing described in this notice.\nContact for privacy questions and requests: support@knistertap.com.\nEffective date: 9 September 2026. Website: https://knistertap.com.'],
        ['Website visits', 'Your browser sends connection information when it requests a page, including an IP address and information needed to deliver the page.\n[CONFIRM HOST / CDN, COUNTRIES, EXACT LOG FIELDS, PURPOSES, RECIPIENTS, AND LOG RETENTION.]\nUmami is the only website analytics tool selected for Knistertap. Its purpose is to understand website usage and improve the pages. No additional analytics tools or advertising trackers are planned. Fonts and artwork are served locally; the website has no third-party embeds or newsletter form.\nAccording to Umami’s documentation, its tracking script does not use cookies: https://docs.umami.is/docs/faq. This does not mean that the hosting and analytics infrastructure receives no connection information.\n[UMAMI INTEGRATION IS PENDING; THE CURRENT PREVIEW DOES NOT LOAD AN ANALYTICS SCRIPT. BEFORE PUBLICATION, CONFIRM THE ACTUAL UMAMI HOST/OPERATOR, SELF-HOSTED OR CLOUD SETUP, PROCESSING COUNTRIES, DATA FIELDS, ACCESS, RETENTION, AND ANY APPLICABLE LEGAL BASIS OR CHOICE MECHANISM. MATCH THIS TEXT TO THE DEPLOYED CONFIGURATION.]'],
        ['Contacting the developer', 'When you email us, we receive your email address, the name you provide, your message, and any attachments. We use that information to respond, investigate the issue you report, and keep the correspondence needed to resolve it. Please do not send passwords, medical records, or information about another person unless it is necessary and you are entitled to share it.\n[EMAIL PROVIDER, PROCESSING COUNTRIES, WHO HAS ACCESS, AND HOW LONG CLOSED SUPPORT REQUESTS ARE KEPT.]'],
        ['Wörtli: game data and sharing', 'Wörtli stores the current daily puzzle day, submitted guesses, game statistics, streak information, and whether you have seen the help screen on your device. This lets the game resume your daily puzzle and display your results. Practice guesses are not saved by the inspected game code.\nThe current implementation includes Apple Game Center. If you are already authenticated with Game Center, Wörtli can submit your guess count and streak when a daily round ends. Opening the leaderboard is not the only trigger for a submission.\nGame Center is an Apple service. Your Game Center profile and scores can be visible to others according to Apple’s service and your settings. Apple describes its handling at https://www.apple.com/legal/privacy/data/en/game-center/. You can manage Game Center through your Apple device settings.\nUsing the game’s share action sends a result summary to the app or recipient you choose. That destination handles the shared information under its own practices.\n[VERIFY THESE DETAILS AGAINST THE RELEASE BUILD. CONFIRM ANY ADS, ANALYTICS, PURCHASES, CLOUD BACKUPS, DIAGNOSTICS AVAILABLE THROUGH APPLE, AND OTHER SDKS; ADD THEM IF USED.]'],
        ['Additional games and services', 'Each additional game covered by this notice will have its own named section explaining its data, purposes, services, and controls. A game with materially different practices will receive an appropriate supplement or separate notice before those practices apply.\n[ADD THE CONFIRMED RELEASE CATALOGUE AND ANY OTHER PROCESSING. DO NOT TREAT THIS WÖRTLI SECTION AS A BLANKET “NO DATA COLLECTED” DECLARATION.]'],
        ['Recipients and international processing', 'Our hosting and email providers process the information described above to deliver those services. Apple and the destinations you choose for sharing handle information as described in the relevant game section. We disclose information where a binding legal obligation requires it.\n[LIST OTHER RECIPIENTS, IF ANY. IDENTIFY ALL RELEVANT PROCESSING COUNTRIES AND ANY REQUIRED TRANSFER SAFEGUARDS. CONFIRM WHETHER THE OPERATOR USES ANY OTHER DISCLOSURES, SALES, OR MARKETING ARRANGEMENTS.]'],
        ['How long information is kept', 'Local Wörtli progress remains in the app’s device storage until that storage is cleared. Deleting rather than offloading the app normally removes its local data; device backups and Apple-held Game Center records are separate. We cannot promise deletion of data held by Apple or a destination you chose for sharing.\nWebsite logs: [PERIOD]. Closed support correspondence: [PERIOD]. Required business records: [CATEGORIES AND APPLICABLE PERIODS]. Backup deletion cycle: [PERIOD].\nWhere a specific record must be kept longer to meet a legal obligation or resolve an active dispute, access should be limited to that purpose. [CONFIRM THE OPERATOR’S ACTUAL RETENTION PROCEDURE.]'],
        ['Your requests and choices', 'You can contact support@knistertap.com to ask what information we hold about you or to request a correction or deletion. Other rights, including objection, restriction, or portability, depend on the law that applies. Where processing depends on consent, you can withdraw that consent for future processing. We may need proportionate information to verify your identity before handling a request.\nYou can raise a concern with the competent data protection authority. [CONFIRM THE OPERATOR’S JURISDICTION, THE RELEVANT AUTHORITY, RESPONSE PROCEDURE, AND ANY REQUIRED REPRESENTATIVE.]'],
        ['Applicable rules and purposes', '[CONFIRM WHICH DATA PROTECTION LAWS APPLY. IF GDPR APPLIES, MAP EACH PROCESSING ACTIVITY TO ITS ACTUAL LEGAL BASIS AND EXPLAIN RELEVANT LEGITIMATE INTERESTS; DO NOT RELY ON A GENERAL CONSENT STATEMENT.]\nReading this notice is not consent to optional tracking or unrelated marketing. Any required choice will be presented separately before the relevant processing begins.'],
        ['Children and sensitive information', 'App age ratings describe content suitability; they do not by themselves establish permission to process children’s data.\n[CONFIRM INTENDED AGES, COUNTRIES, WHETHER CHILDREN ARE TARGETED, AND THE PARENTAL OR OTHER SAFEGUARDS REQUIRED BY THE ACTUAL FEATURES.]\nKnistertap’s recreational games are not a channel for submitting diagnoses or clinical records. Any future study involving health information would require its own explanation and participation arrangements; it is not covered merely by visiting this website.'],
        ['Changes to this notice', 'We will update this notice when the described practices change and identify the effective date. Where a material change requires additional notice or a new choice, we will provide it before applying the change. Questions can be sent to support@knistertap.com.'],
      ],
    },
    terms: {
      title: 'Terms of Service',
      intro: 'These draft terms describe the proposed rules for Knistertap’s website and associated game services. Complete the operator details and confirm how the terms will be presented and accepted before using them as binding terms.',
      sections: [
        ['About Knistertap and these terms', 'The operator’s identity and postal address are listed in the legal notice: /en/legal/. Contact: support@knistertap.com. Effective date: 9 September 2026.\nThese terms cover this website and Knistertap-operated services expressly identified as using them. They do not replace an app’s applicable software licence, Apple’s service terms, or any mandatory rights you have. Where contractual agreement is required, the relevant terms must be presented through an appropriate acceptance process.'],
        ['What the games are for', 'Knistertap creates recreational games that invite you to work with words, patterns, and small challenges. They are for entertainment and everyday mental activity.\nWe do not promise a particular improvement in memory, literacy, attention, intelligence, or health. The games are not diagnostic tools or treatments for neurological or other medical conditions. A founder’s research interests do not establish that a game has been clinically validated.'],
        ['App licences and Apple services', 'An app downloaded from the App Store is licensed under Apple’s Standard End User License Agreement unless the app provides a valid custom agreement. See https://www.apple.com/legal/internet-services/itunes/dev/stdeula/. These website and service terms are not a replacement custom EULA.\nFeatures such as Game Center are also subject to the relevant Apple terms and settings. Knistertap cannot guarantee the availability of a service operated by another provider.'],
        ['Eligibility and fair play', 'Follow the app’s age rating and the eligibility rules of the platform and services you use. If local law requires a parent or guardian’s involvement, obtain it before entering a contract or using a feature that requires it. [CONFIRM ANY ADDITIONAL MINIMUM AGE.]\nDo not interfere with the website or games, access systems without permission, submit fraudulent leaderboard results, distribute malicious content, or infringe another person’s rights. These rules do not restrict activities that applicable law expressly permits.'],
        ['Prices, purchases, and subscriptions', 'A game’s current price and any paid features are shown in its store listing or purchase screen before a transaction. If purchases are offered through Apple, payment, subscription management, cancellation, and refund requests follow the applicable Apple process and your mandatory consumer rights.\n[CONFIRM WHICH GAMES ARE FREE OR PAID AND WHETHER IN-APP PURCHASES, SUBSCRIPTIONS, ADS, OR DIRECT SALES EXIST. REMOVE INAPPLICABLE LANGUAGE AND ADD THE ACTUAL COMMERCIAL TERMS. NO SUBSCRIPTION IS CREATED BY VISITING THIS WEBSITE.]'],
        ['Availability, progress, and updates', 'We work to keep the games usable and resolve reported problems. Bugs, maintenance, device changes, and interruptions in external services can affect play, progress, or leaderboard submissions. Keep your device and app up to date.\nFeatures and supported versions may change. Where a change affects a paid entitlement or requires notice or a remedy under applicable law, those obligations remain. We do not promise indefinite availability, but these terms do not remove mandatory rights to updates or remedies.'],
        ['Our work and your feedback', 'Knistertap’s original code, artwork, names, and website content remain the property of their owners. Playing a game does not transfer ownership of those materials. Third-party materials remain subject to their own licences.\nYou retain rights in original material you send us. By sending feedback or a bug report, you permit us to use it to understand the issue and improve the relevant service. This is not permission to publish private correspondence or sensitive personal information.'],
        ['Privacy and separate research', 'The Privacy Policy explains the actual handling of personal information, with game-specific sections where needed. Accepting these terms is not blanket consent to optional tracking, marketing, or research.\nParticipation in any future study would be voluntary and subject to separate information and agreements. Playing a recreational game does not itself enrol you in research.'],
        ['Responsibility and legal rights', 'Nothing in these terms excludes or limits liability or consumer rights that cannot lawfully be excluded or limited. We do not exclude liability for intentional misconduct or gross negligence.\n[HAVE THE FINAL WARRANTY AND LIABILITY POSITION REVIEWED FOR THE OPERATOR’S COUNTRY AND TARGET MARKETS. NO ARBITRARY MONETARY LIABILITY CAP, MANDATORY ARBITRATION, OR CLASS-ACTION WAIVER IS INCLUDED IN THIS DRAFT.]'],
        ['Stopping use and addressing misuse', 'You can stop using the website or a game at any time. Uninstalling an app does not necessarily cancel a subscription or erase records held by Apple; use the relevant platform controls if those features apply.\nWhere Knistertap operates an online feature, proportionate restrictions may be used to address material misuse or protect security, subject to applicable rights and notice requirements. This does not give us a right to erase your local data remotely. Contact support@knistertap.com if you believe a restriction was a mistake.'],
        ['Changes, disputes, and contact', 'We will identify the date of revised terms and provide appropriate notice of material changes. Where fresh agreement is required, we will request it rather than relying solely on continued browsing.\n[CONFIRM GOVERNING LAW AND ANY PERMITTED FORUM WITHOUT DISPLACING MANDATORY CONSUMER PROTECTION. THE OPERATOR’S DOMICILE HAS NOT BEEN SUPPLIED.]\nPlease contact support@knistertap.com with a question or concern. This does not prevent you from seeking a remedy through a court, authority, or dispute-resolution body available under applicable law.'],
      ],
    },
    legal: {title:'Legal notice', draft:false, intro:'Knistertap is operated by Candoo Labs / Wolke. This page provides the operator’s identity and contact details.', sections:[['Operator','Candoo Labs / Wolke\nZaehlerweg 5\n6300 Zug\nSwitzerland'],['Contact','Email for website, game support and privacy enquiries: support@knistertap.com\nWebsite: https://knistertap.com\nLast updated: 9 September 2026.']]},
  },
};
policies.de = {
  privacy: {
    title: 'Datenschutzerklärung',
    intro: 'Diese Erklärung beschreibt den Umgang mit Personendaten beim Besuch dieser Website, beim Kontakt mit dem Entwickler und bei der Nutzung der unten genannten Spiele. Die Angaben zu einzelnen Spielen ergänzen die gemeinsamen Informationen. Nicht jedes Spiel bearbeitet dieselben Daten.',
    sections: [
      ['Wer ist verantwortlich?', 'Identität und Postanschrift des Betreibers findest du im Impressum: /de/legal/. Dieser Betreiber ist für die hier beschriebene Datenbearbeitung verantwortlich.\nKontakt für Datenschutzfragen und Anfragen: support@knistertap.com.\nGültig ab: 9. September 2026. Website: https://knistertap.com.'],
      ['Besuch der Website', 'Dein Browser übermittelt beim Abruf einer Seite Verbindungsinformationen, darunter eine IP-Adresse und die für die Auslieferung der Seite benötigten Angaben.\n[HOST / CDN, LÄNDER, KONKRETE PROTOKOLLDATEN, ZWECKE, EMPFÄNGER UND AUFBEWAHRUNGSDAUER BESTÄTIGEN.]\nFür die Website-Analyse ist ausschliesslich Umami vorgesehen. Damit möchten wir die Nutzung der Website verstehen und die Seiten verbessern. Weitere Analytics-Tools oder Werbetracker sind nicht vorgesehen. Schriften und Bilder werden lokal ausgeliefert; die Website enthält keine eingebetteten Drittanbieterdienste und keine Newsletter-Anmeldung.\nLaut Umamis Dokumentation verwendet das Tracking-Skript keine Cookies: https://docs.umami.is/docs/faq. Das bedeutet nicht, dass die Hosting- und Analytics-Infrastruktur keine Verbindungsinformationen erhält.\n[DIE UMAMI-EINBINDUNG STEHT NOCH AUS; DIE AKTUELLE VORSCHAU LÄDT KEIN ANALYTICS-SKRIPT. VOR VERÖFFENTLICHUNG DEN UMAMI-HOST/BETREIBER, EIGENBETRIEB ODER CLOUD, BEARBEITUNGSLÄNDER, DATENFELDER, ZUGRIFF, AUFBEWAHRUNG UND ALLFÄLLIGE RECHTSGRUNDLAGE ODER AUSWAHLMÖGLICHKEIT BESTÄTIGEN. DEN TEXT MIT DER TATSÄCHLICHEN KONFIGURATION ABGLEICHEN.]'],
      ['Kontakt mit dem Entwickler', 'Wenn du uns eine E-Mail schreibst, erhalten wir deine E-Mail-Adresse, den angegebenen Namen, deine Nachricht und allfällige Anhänge. Wir verwenden diese Angaben, um zu antworten, das gemeldete Problem zu untersuchen und die für seine Lösung nötige Korrespondenz zu führen. Bitte sende keine Passwörter, medizinischen Unterlagen oder Angaben über andere Personen, ausser dies ist erforderlich und du darfst sie weitergeben.\n[E-MAIL-ANBIETER, BEARBEITUNGSLÄNDER, ZUGRIFFSBERECHTIGTE UND AUFBEWAHRUNGSDAUER ERLEDIGTER SUPPORTANFRAGEN ERGÄNZEN.]'],
      ['Wörtli: Spieldaten und Teilen', 'Wörtli speichert den Tag des aktuellen Tagesrätsels, eingegebene Versuche, Spielstatistiken, Serien und den Status der Hilfeanzeige auf deinem Gerät. So kannst du das Tagesrätsel fortsetzen und deine Ergebnisse ansehen. Versuche im Übungsmodus werden im geprüften Spielcode nicht gespeichert.\nDie aktuelle Umsetzung enthält Apple Game Center. Wenn du dort bereits angemeldet bist, kann Wörtli nach Abschluss einer Tagesrunde die Anzahl deiner Versuche und deine Serie übermitteln. Das Öffnen der Rangliste ist nicht der einzige Auslöser einer Übermittlung.\nGame Center ist ein Dienst von Apple. Dein Game-Center-Profil und deine Ergebnisse können gemäss Apples Dienst und deinen Einstellungen für andere sichtbar sein. Apples Angaben findest du unter https://www.apple.com/legal/privacy/data/en/game-center/. Game Center lässt sich über die Einstellungen deines Apple-Geräts verwalten.\nMit der Teilen-Funktion übergibst du eine Ergebniszusammenfassung an die von dir gewählte App oder Person. Für die anschliessende Bearbeitung gelten die Regeln dieses Ziels.\n[DIE ANGABEN MIT DER RELEASE-VERSION ABGLEICHEN. WERBUNG, ANALYSE, KÄUFE, CLOUD-BACKUPS, ÜBER APPLE VERFÜGBARE DIAGNOSEDATEN UND WEITERE SDKS BESTÄTIGEN UND GEGEBENENFALLS ERGÄNZEN.]'],
      ['Weitere Spiele und Dienste', 'Jedes zusätzliche Spiel unter dieser Erklärung erhält einen eigenen Abschnitt über Daten, Zwecke, Dienste und Einstellungsmöglichkeiten. Bei wesentlich anderen Praktiken wird vor deren Anwendung eine passende Ergänzung oder eigene Erklärung bereitgestellt.\n[BESTÄTIGTEN SPIELEKATALOG UND WEITERE BEARBEITUNGEN ERGÄNZEN. DIE WÖRTLI-ANGABEN SIND KEINE PAUSCHALE ERKLÄRUNG, DASS KEINE DATEN ERHOBEN WERDEN.]'],
      ['Empfänger und Bearbeitung im Ausland', 'Unsere Hosting- und E-Mail-Anbieter bearbeiten die oben beschriebenen Informationen zur Erbringung ihrer Dienste. Apple sowie die von dir gewählten Ziele beim Teilen bearbeiten Daten wie im jeweiligen Spieleabschnitt beschrieben. Bei einer verbindlichen gesetzlichen Pflicht geben wir die erforderlichen Angaben weiter.\n[WEITERE EMPFÄNGER, ALLE RELEVANTEN BEARBEITUNGSLÄNDER UND ERFORDERLICHE GARANTIEN FÜR AUSLANDÜBERMITTLUNGEN ERGÄNZEN. WEITERE WEITERGABEN, VERKÄUFE ODER MARKETINGVEREINBARUNGEN DES BETREIBERS BESTÄTIGEN.]'],
      ['Wie lange Daten bleiben', 'Lokale Wörtli-Spielstände bleiben im Datenspeicher der App, bis dieser gelöscht wird. Das Löschen statt Auslagern der App entfernt normalerweise ihre lokalen Daten. Gerätebackups und bei Apple gespeicherte Game-Center-Daten sind davon getrennt. Wir können keine Löschung von Daten zusagen, die Apple oder ein von dir gewähltes Ziel beim Teilen verwaltet.\nWebsite-Protokolle: [DAUER]. Erledigte Supportkorrespondenz: [DAUER]. Gesetzlich erforderliche Geschäftsunterlagen: [KATEGORIEN UND FRISTEN]. Löschzyklus für Backups: [DAUER].\nMuss ein bestimmter Datensatz wegen einer gesetzlichen Pflicht oder eines laufenden Rechtsstreits länger bleiben, soll der Zugriff auf diesen Zweck beschränkt sein. [TATSÄCHLICHES AUFBEWAHRUNGSVERFAHREN BESTÄTIGEN.]'],
      ['Deine Anfragen und Möglichkeiten', 'Du kannst dich an support@knistertap.com wenden, um Auskunft über bei uns vorhandene Angaben zu erhalten oder eine Berichtigung oder Löschung zu verlangen. Weitere Rechte wie Widerspruch, Einschränkung oder Datenübertragbarkeit hängen vom anwendbaren Recht ab. Beruht eine Bearbeitung auf einer Einwilligung, kannst du sie für die Zukunft widerrufen. Vor der Bearbeitung einer Anfrage können angemessene Angaben zur Identitätsprüfung nötig sein.\nDu kannst dich an die zuständige Datenschutzbehörde wenden. Für den Schweizer Betreiber ist dies der Eidgenössische Datenschutz- und Öffentlichkeitsbeauftragte (EDÖB): https://www.edoeb.admin.ch/. Zuständigkeiten weiterer Behörden nach anwendbarem Recht bleiben bestehen. [ANTWORTVERFAHREN UND ALLFÄLLIGE ERFORDERLICHE VERTRETUNG ERGÄNZEN.]'],
      ['Anwendbare Regeln und Zwecke', 'Für den Schweizer Betreiber gilt das schweizerische Datenschutzrecht. [WEITERE ANWENDBARE REGELN PRÜFEN. FALLS DIE DSGVO GILT, JEDE BEARBEITUNG IHRER TATSÄCHLICHEN RECHTSGRUNDLAGE ZUORDNEN UND RELEVANTE BERECHTIGTE INTERESSEN ERLÄUTERN; KEINE PAUSCHALE EINWILLIGUNG VERWENDEN.]\nDas Lesen dieser Erklärung ist keine Einwilligung in optionales Tracking oder sachfremdes Marketing. Erforderliche Entscheidungen werden vor Beginn der jeweiligen Bearbeitung gesondert angeboten.'],
      ['Kinder und besonders schützenswerte Angaben', 'Altersfreigaben im App Store betreffen die Eignung von Inhalten. Sie begründen für sich allein keine Erlaubnis zur Bearbeitung von Daten von Kindern.\n[ZIELALTER, LÄNDER, AUSRICHTUNG AUF KINDER UND DIE FÜR DIE TATSÄCHLICHEN FUNKTIONEN ERFORDERLICHEN SCHUTZMASSNAHMEN BESTÄTIGEN.]\nDie Freizeitspiele von Knistertap sind kein Kanal zur Übermittlung von Diagnosen oder klinischen Unterlagen. Eine spätere Studie mit Gesundheitsdaten würde eigene Informationen und Teilnahmebedingungen benötigen. Ein Website-Besuch ist keine solche Teilnahme.'],
      ['Änderungen dieser Erklärung', 'Wir aktualisieren diese Erklärung, wenn sich die beschriebenen Praktiken ändern, und nennen das Gültigkeitsdatum. Erfordert eine wesentliche Änderung eine zusätzliche Information oder eine neue Entscheidung, erfolgt dies vor ihrer Anwendung. Fragen kannst du an support@knistertap.com richten.'],
    ],
  },
  terms: {
    title: 'Nutzungsbedingungen',
    intro: 'Dieser Entwurf beschreibt die vorgesehenen Regeln für Knistertaps Website und zugehörige Spieledienste. Ergänze die offenen Angaben und bestätige die Art der Bereitstellung und Zustimmung, bevor du ihn als verbindliche Bedingungen verwendest.',
    sections: [
      ['Über Knistertap und diese Bedingungen', 'Identität und Postanschrift des Betreibers findest du im Impressum: /de/legal/. Kontakt: support@knistertap.com. Gültig ab: 9. September 2026.\nDiese Bedingungen betreffen die Website und vom Betreiber angebotene Dienste, die ausdrücklich darauf verweisen. Sie ersetzen weder die Softwarelizenz einer App noch Apples Dienstbedingungen oder zwingende Rechte. Wo eine vertragliche Zustimmung nötig ist, müssen die relevanten Bedingungen in einem geeigneten Zustimmungsverfahren vorgelegt werden.'],
      ['Wozu die Spiele gedacht sind', 'Knistertap entwickelt Freizeitspiele rund um Wörter, Muster und kleine Herausforderungen. Sie dienen der Unterhaltung und alltäglichen geistigen Aktivität.\nWir versprechen keine bestimmte Verbesserung von Gedächtnis, Lesen und Schreiben, Aufmerksamkeit, Intelligenz oder Gesundheit. Die Spiele sind keine Diagnosewerkzeuge und keine Behandlung neurologischer oder anderer Erkrankungen. Forschungsinteressen des Gründers bedeuten nicht, dass ein Spiel klinisch validiert ist.'],
      ['App-Lizenzen und Apple-Dienste', 'Eine aus dem App Store geladene App wird unter Apples Standard-Endbenutzer-Lizenzvertrag lizenziert, sofern die App keinen gültigen eigenen Vertrag bereitstellt: https://www.apple.com/legal/internet-services/itunes/dev/stdeula/. Diese Website- und Dienstbedingungen ersetzen diesen Lizenzvertrag nicht.\nFür Funktionen wie Game Center gelten zusätzlich die relevanten Apple-Bedingungen und Einstellungen. Knistertap kann die Verfügbarkeit von Diensten anderer Anbieter nicht garantieren.'],
      ['Voraussetzungen und faires Spielen', 'Beachte die Altersfreigabe der App und die Teilnahmevoraussetzungen der verwendeten Plattformen und Dienste. Verlangt das örtliche Recht die Mitwirkung einer erziehungsberechtigten Person, hole diese vor einem Vertragsabschluss oder der Nutzung einer entsprechenden Funktion ein. [ALLFÄLLIGES ZUSÄTZLICHES MINDESTALTER BESTÄTIGEN.]\nStöre Website und Spiele nicht, greife nicht unberechtigt auf Systeme zu, manipuliere keine Ranglisten, verbreite keine schädlichen Inhalte und verletze keine Rechte anderer. Gesetzlich ausdrücklich erlaubte Tätigkeiten werden dadurch nicht eingeschränkt.'],
      ['Preise, Käufe und Abonnemente', 'Diese Website stellt Spiele vor und bietet Informationen und Support. Sie nimmt keine Bestellungen oder Zahlungen entgegen. Der aktuelle Preis eines Spiels und kostenpflichtige Funktionen werden vor einer Transaktion im Store-Eintrag oder Kaufdialog angezeigt. Werden Käufe über Apple angeboten, richten sich Zahlung, Aboverwaltung, Kündigung und Erstattungsanfragen nach dem anwendbaren Apple-Verfahren und deinen zwingenden Verbraucherrechten.\n[KOSTENLOSE UND KOSTENPFLICHTIGE SPIELE, IN-APP-KÄUFE, ABOS, WERBUNG DER APPS BESTÄTIGEN. UNZUTREFFENDES ENTFERNEN UND TATSÄCHLICHE GESCHÄFTSBEDINGUNGEN ERGÄNZEN. EIN WEBSITE-BESUCH ERÖFFNET KEIN ABO.]'],
      ['Verfügbarkeit, Spielstände und Updates', 'Wir arbeiten daran, die Spiele nutzbar zu halten und gemeldete Probleme zu beheben. Fehler, Wartung, Geräteänderungen und Ausfälle externer Dienste können das Spielen, Spielstände oder Ranglistenübermittlungen beeinträchtigen. Halte Gerät und App aktuell.\nFunktionen und unterstützte Versionen können sich ändern. Betrifft eine Änderung einen bezahlten Anspruch oder verlangt das anwendbare Recht eine Information oder Abhilfe, bleiben diese Pflichten bestehen. Wir versprechen keine unbegrenzte Verfügbarkeit; zwingende Ansprüche auf Updates oder Abhilfe werden dadurch nicht aufgehoben.'],
      ['Unsere Arbeit und dein Feedback', 'Originalcode, Gestaltung, Namen und Website-Inhalte von Knistertap bleiben Eigentum der jeweiligen Berechtigten. Das Spielen überträgt kein Eigentum an diesen Materialien. Für Drittmaterialien gelten die jeweiligen Lizenzen.\nDu behältst Rechte an eigenen Inhalten, die du uns sendest. Mit Feedback oder einer Fehlermeldung erlaubst du die Verwendung zur Untersuchung des Problems und Verbesserung des betreffenden Dienstes. Dies ist keine Erlaubnis zur Veröffentlichung privater Korrespondenz oder sensibler Personendaten.'],
      ['Datenschutz und gesonderte Forschung', 'Die Datenschutzerklärung beschreibt den tatsächlichen Umgang mit Personendaten und enthält bei Bedarf Abschnitte zu einzelnen Spielen. Die Zustimmung zu diesen Bedingungen ist keine pauschale Einwilligung in optionales Tracking, Marketing oder Forschung.\nEine spätere Studienteilnahme wäre freiwillig und würde eigene Informationen und Vereinbarungen erfordern. Das Spielen eines Freizeitspiels meldet dich nicht zu Forschung an.'],
      ['Verantwortung und gesetzliche Rechte', 'Diese Bedingungen schliessen weder Haftung noch Verbraucherrechte aus, soweit ein solcher Ausschluss oder eine Einschränkung gesetzlich unzulässig ist. Die Haftung für absichtliches oder grobfahrlässiges Verhalten wird nicht ausgeschlossen.\n[DIE ENDGÜLTIGEN GEWÄHRLEISTUNGS- UND HAFTUNGSREGELN FÜR DEN BETREIBER UND SEINE ZIELMÄRKTE PRÜFEN LASSEN. DIESER ENTWURF ENTHÄLT KEINE WILLKÜRLICHE HAFTUNGSSUMME, OBLIGATORISCHE SCHIEDSKLAUSEL ODER VERZICHTSERKLÄRUNG FÜR SAMMELKLAGEN.]'],
      ['Nutzung beenden und Missbrauch behandeln', 'Du kannst die Website oder ein Spiel jederzeit nicht mehr nutzen. Das Deinstallieren beendet nicht zwingend ein Abo und löscht keine von Apple verwalteten Datensätze. Nutze gegebenenfalls die entsprechenden Plattformfunktionen.\nFür von Knistertap betriebene Onlinefunktionen können verhältnismässige Beschränkungen bei erheblichem Missbrauch oder zum Schutz der Sicherheit erfolgen, unter Beachtung anwendbarer Rechte und Informationspflichten. Daraus folgt kein Recht, lokale Daten auf deinem Gerät aus der Ferne zu löschen. Bei einer möglicherweise irrtümlichen Beschränkung kontaktiere support@knistertap.com.'],
      ['Änderungen, Streitfragen und Kontakt', 'Geänderte Bedingungen erhalten ein Datum. Über wesentliche Änderungen informieren wir angemessen. Wo eine erneute Zustimmung erforderlich ist, holen wir diese ein, statt allein auf weiteres Surfen zu vertrauen.\nAls vorgesehene Rechtswahl gilt schweizerisches Recht. Zwingender Schutz nach dem Recht deines gewöhnlichen Aufenthalts und zwingende Gerichtsstände bleiben unberührt. [ENDGÜLTIGE RECHTSWAHL UND ZIELMÄRKTE PRÜFEN; ES WIRD KEIN AUSSCHLIESSLICHER GERICHTSSTAND VORGEGEBEN.]\nBei Fragen wende dich an support@knistertap.com. Das hindert dich nicht daran, nach anwendbarem Recht ein Gericht, eine Behörde oder eine Schlichtungsstelle anzurufen.'],
    ],
  },
  legal: {title:'Impressum', draft:false, intro:'Knistertap wird von Candoo Labs / Wolke betrieben. Hier findest du die Angaben zum Betreiber und die Kontaktmöglichkeiten.', sections:[['Betreiber','Candoo Labs / Wolke\nZaehlerweg 5\n6300 Zug\nSchweiz'],['Kontakt','E-Mail für Fragen zur Website, Spielesupport und Datenschutz: support@knistertap.com\nWebsite: https://knistertap.com\nStand: 9. September 2026.']]},
};
for (const p of Object.values(policies.en)) p.sections = p.sections.map(([title, body]) => [title, body.replaceAll('[LEGAL NAME / COMPANY]', 'Candoo Labs / Wolke').replaceAll('[PUBLIC BUSINESS ADDRESS, COUNTRY]', 'Zaehlerweg 5, 6300 Zug, Switzerland').replaceAll('[PUBLIC BUSINESS ADDRESS]', 'Zaehlerweg 5, 6300 Zug').replaceAll('[COUNTRY]', 'Switzerland').replace('[CONFIRM THE OPERATOR’S JURISDICTION, THE RELEVANT AUTHORITY, RESPONSE PROCEDURE, AND ANY REQUIRED REPRESENTATIVE.]', 'For this Swiss operator, the relevant authority is the Federal Data Protection and Information Commissioner: https://www.edoeb.admin.ch/. Other competent authorities remain available under applicable law. [CONFIRM RESPONSE PROCEDURE AND ANY REQUIRED REPRESENTATIVE.]').replace('[CONFIRM WHICH DATA PROTECTION LAWS APPLY.', 'Swiss data protection law applies to this Swiss operator. [CONFIRM ANY OTHER APPLICABLE LAWS.').replace('[CONFIRM GOVERNING LAW AND ANY PERMITTED FORUM WITHOUT DISPLACING MANDATORY CONSUMER PROTECTION. THE OPERATOR’S DOMICILE HAS NOT BEEN SUPPLIED.]', 'The proposed governing law is Swiss law. Mandatory protection under the law of your habitual residence and mandatory jurisdiction rules remain unaffected. [REVIEW THE FINAL CHOICE OF LAW FOR THE TARGET MARKETS. NO EXCLUSIVE COURT IS SPECIFIED.]')]);
